petstagram/main_app/urls.py
from django.urls import path

from petstagram.main_app.views import show_home, show_dashboard, show_profile, show_photo_details, like_pet

urlpatterns = (
    path('', show_home, name='index'),
    path('dashboard/', show_dashboard, name='dashboard'),
    path('profile/', show_profile, name='profile'),
    path('photo/details/<int:pk>/', show_photo_details, name='photo details'),
    path('photo/like/<int:pk>/', like_pet,  name='like pet photo'),
)

petstagram/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from petstagram import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram.main_app.urls')),
]

if settings.DEBUG: #add this
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petstagram/main_app/models.py
import datetime

from django import forms
from django.db import models
from django.core.validators import MinLengthValidator
from django.forms import ModelForm

from petstagram.main_app.validators import only_letters, validate_max_size


# Create your models here.


class Profile(models.Model):
    MALE = "Male"
    FEMALE = "Female"
    DO_NOT_SHOW = "Do not show"
    GENDER = [(x, x) for x in (MALE, FEMALE, DO_NOT_SHOW)]

    first_name = models.CharField(
        max_length=30,
        validators=[
            MinLengthValidator(2), only_letters,
        ]
    )
    last_name = models.CharField(
        max_length=30,
        validators=[
            MinLengthValidator(2), only_letters,
        ]
    )
    picture = models.URLField()

    date_of_birth = models.DateField(
        null=True,
        blank=True,
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    email = models.EmailField(
        null=True,
        blank=True,
    )

    gender = models.CharField(
        max_length=max(len(x) for x, _ in GENDER),
        choices=GENDER,
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Pet(models.Model):

    CAT = "Cat"
    DOG = "Dog"
    BUNNY = "Bunny"
    FISH = "Fish"
    OTHER = "Other"
    PETS = [(x, x) for x in (CAT, DOG, BUNNY, FISH, OTHER)]

    name = models.CharField(max_length=30,)

    pets_type = models.CharField(
        max_length=max(len(x) for x, y in PETS),
        choices=PETS,
    )
    date_of_birth = models.DateField(
        null=True,
        blank=True,
    )
    user_profile = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,

    )

    @property
    def age(self):
        return datetime.date.today().year - self.date_of_birth.year

    def __str__(self):
        return f"{self.name} {self.pets_type}"

    class Meta:
        unique_together = ('user_profile', 'name')


class PetPhoto(models.Model):
    photo = models.ImageField(
        upload_to='images/',
        validators=(validate_max_size,)
    )
    tagged_pets = models.ManyToManyField(
        Pet,
        # Validate at least one Pet ( to do )
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    publication_date = models.DateTimeField(
        auto_now_add=True,
    )

    likes = models.IntegerField(default=0,)

petstagram/main_app/forms.py
from django import forms

petstagram/main_app/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from petstagram.main_app.models import Profile, PetPhoto


# Create your views here.
def get_profile():
    profiles = Profile.objects.all()
    if profiles:
        return profiles[0]
    return None


def show_home(request):

    context = {
        'hide_additional_nav_items': True
    }
    return render(request, "home_page.html", context)


def show_dashboard(request):
    profile = get_profile()

    if not profile:
        return redirect('401')

    pet_photos = set(PetPhoto.objects.filter(tagged_pets__user_profile=profile))
    context = {
        'pet_photos': pet_photos,
    }
    return render(request, "dashboard.html", context)


def show_profile(request):
    profile = get_profile()
    pet_photos = PetPhoto.objects.filter(tagged_pets__user_profile=profile).distinct()
    total_images = len(pet_photos)
    total_like_count = sum(pp.likes for pp in pet_photos)

    context = {
        'profile': profile,
        'total_images': total_images,
        'total_images_likes': total_like_count,

    }
    return render(request, "profile_details.html", context)


def show_photo_details(request, pk):
    pet_photo = PetPhoto.objects.get(pk=pk)
    context = {
        'pet_photo': pet_photo,
    }
    return render(request, "photo_details.html", context)


def like_pet(request, pk):
    pet_photo = PetPhoto.objects.get(pk=pk)
    pet_photo.likes += 1
    pet_photo.save()
    return redirect('photo details', pk)

petstagram/main_app/templates/401_error.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<div class="container mb-5 mt-2">
    <div class="jumbotron">
        <img style="width: 100%"
             src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
        <div class="position-sticky">
            <h1 class="display-4">401 Unauthorized</h1>
            <p class="lead">You should create a profile to open this page!</p>
            <hr class="my-4">
            <div class="row col-lg-6">

                <!-- Button to show when profile is NOT created -->
                <a href="#" class="btn btn-lg btn-secondary">Create Profile</a>
            </div>
        </div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>

</body>
</html>

petstagram/main_app/templates/home_page.html
{% extends 'base.html' %}

{% block page_content %}
    <div class="jumbotron parent">
        <img style="width: 100%"
             src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
        <div class="absolute">
            <h1 class="display-4">Welcome to Petstagram</h1>
            <p class="lead">Share your pets photos.</p>
            <hr class="my-4">
            <div class="inner cover">
                <h1 class="cover-heading"></h1>
                <div class="row">

                    <!-- Button to show if profile created -->
                    <div class="col-lg-6">
                        <p class="lead">
                            {% if hp %}
                                <a href="#" class="btn btn-lg btn-secondary">Enter</a></p>
                            {% else %}
                                <a href="#" class="btn btn-lg btn-secondary">Create Profile</a>
                            {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

petstagram/main_app/templates/pet_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Pet</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Photo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<!-- End Navigation Bar -->

<div class="container">
    <h1 class="text-center">Add Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="container mb-5" action="profile_details.html">

                <!-- Form for Adding a Pet Info -->

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer">
    <span class="text-muted">@2022 Python Web Basics Workshop at SoftUni</span>
</footer>
<!-- End Page Footer -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>

</html>

petstagram/main_app/templates/pet_delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Pet</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Photo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<!-- End Navigation Bar -->

<div class="container">
    <h1 class="text-center">Delete Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="profile_details.html">

                <!-- Form for Deleting a Pet Info -->

                <button class="btn btn-danger mt-2" type="submit">Delete</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer ">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>

</html>

petstagram/main_app/templates/pet_edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Pet</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Photo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<!-- End Navigation Bar -->

<div class="container">
    <h1 class="text-center">Edit Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="profile_details.html">

                <!-- Form for Editing a Pet Info -->

                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer ">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>

</html>

petstagram/main_app/templates/photo_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Pet</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Photo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<!-- End Navigation Bar -->

<div class="container">
    <h1 class="text-center">Add a New Pet Photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="POST" action="dashboard.html">

                <!-- Form for Adding Photos -->

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer ">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>

</html>

petstagram/main_app/templates/photo_details.html
{% extends 'base.html' %}

{% block page_content %}
    <div class="d-flex">
        <div class="d-inline p-2 w-50">
            <!-- Image -->
            <img src="{{ pet_photo.photo.url }}"
                 class="w-100 rounded mx-auto d-block" alt="Photo description">
        </div>
        <div class="d-inline p-2 w-50">
            {%  for pet in pet_photo.tagged_pets.all %}
            <!-- Info for First Pet -->
            <div class="d-flex justify-content-around">
                <h5><u>Type:</u> {{ pet.pets_type }}</h5>
                <h5><u>Name:</u> {{ pet.name }}</h5>
                {% if pet.date_of_birth %}
                <h5><u>Age:</u> {{ pet.age }}</h5>
                {% endif %}
            </div>
            {%  endfor %}
            <!-- Description -->
            <p class="mt-2">Description: {{ pet_photo.description}}</p>
            <!-- Likes Button -->
            <a href="{% url 'like pet photo' pet_photo.id %}"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
            <!-- Likes Counter -->
            <p class="mt-2">Likes: {{ pet_photo.likes }}</p>
            <!-- Buttons -->
            <a href="#" class="btn btn-primary">Edit</a>
            <a href="#" class="btn btn-danger">Delete</a>
        </div>
    </div>
{% endblock %}

petstagram/main_app/templates/profile_create-old.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index-page' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile-page' %}">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    <h1 class="text-center">Create Your Profile</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form>
                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control" name="first_name" maxlength="30" required
                           placeholder="Enter first name" id="first_name"/>
                </div>
                <div class="form-group">
                    <label for="id_last_name">Last Name</label>
                    <input type="text" class="form-control" name="last_name" maxlength="30" required
                           placeholder="Enter last name" id="id_last_name"/>
                </div>
                <div class="form-group">
                    <label for="id_image">Link to Profile Image</label>
                    <input type="url" class="form-control" name="profile_image" required id="id_image"
                    placeholder="Enter URL"/>
                </div>
                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer ">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>

</html>